# WEEK 2: RAG PIPELINE WITH BM25 + PAGEINDEX + GEMINI

In [ ]:
!pip install langchain langchain-community langchain-google-genai pageindex rank-bm25

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.3.1)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.2)
Requirement already satisfied: langchain-google-genai in /usr/local/lib/python3.12/dist-packages (4.2.4)
Requirement already satisfied: pageindex in /usr/local/lib/python3.12/dist-packages (0.2.8)
Requirement already satisfied: rank-bm25 in /usr/local/lib/python3.12/dist-packages (0.2.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.4.0)
Requirement already satisfied: langgraph<1.3.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.1)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.7)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.8.5)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.14.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.49)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<3.0.0,>=1.65.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.68.0)
Requirement already satisfied: openai>=1.70.0 in /usr/local/lib/python3.12/dist-packages (from pageindex) (2.37.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (2.47.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.28.1)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.0->langchain) (4.1.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.0->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.0->langchain) (0.3.14)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.0->langchain) (3.7.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.70.0->pageindex) (0.15.0)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai>=1.70.0->pageindex) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.5.20)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (4.9.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.0->langchain) (1.12.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<3.0.0,>=1.65.0->langchain-google-genai) (0.6.3)

In [50]:
# ── SECTION 0: Set up API Keys ─────────────────────────────

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")
PAGEINDEX_API_KEY = userdata.get("PAGEINDEX")
print("GOOGLE_API_KEY found:", os.environ["GOOGLE_API_KEY"] is not None)
print("PAGEINDEX found:", PAGEINDEX_API_KEY is not None)

GOOGLE_API_KEY found: True
PAGEINDEX found: True

## Corpus Preparation

In [ ]:
# ── SECTION 1.1: Load the raw CSV data ──────────────────────
import pandas as pd

df = pd.read_csv('data.csv')
df

,url,title,text,tokens,token_count
0,https://www.bbc.com/news/articles/crlp991nw41o,Why the AI industry is the real winner of the ...,It is not only OpenAI but the AI race itself t...,"['it', 'is', 'not', 'only', 'openai', 'but', '...",946
1,https://www.bbc.com/future/article/20260519-go...,Google's AI is being manipulated. The search g...,A BBC investigation revealed a simple way AI c...,"['a', 'bbc', 'investigation', 'revealed', 'a',...",1860
2,https://www.bbc.com/news/articles/cvgz1ynq1nqo,Google to release first smart glasses since Go...,More than a decade after its famed Google Glas...,"['more', 'than', 'a', 'decade', 'after', 'its'...",672
3,https://www.bbc.com/news/articles/crep3v8vzglo,Standard Chartered to cut thousands of roles a...,Banking giant Standard Chartered has become th...,"['banking', 'giant', 'standard', 'chartered', ...",463
4,https://www.bbc.com/news/articles/c4g04qkqlk2o,Samsung strike on hold as workers push for AI ...,The largest union at Samsung Electronics has s...,"['the', 'largest', 'union', 'at', 'samsung', '...",789
5,https://www.bbc.com/future/article/20260505-ho...,'Think outside the bots': How to stop AI from ...,GPS ruined our sense of direction. Search engi...,"['gps', 'ruined', 'our', 'sense', 'of', 'direc...",2153
6,https://www.bbc.com/news/articles/c0q2gkj97eko,Robo-top: The machines that could make your ne...,"They assemble cars, perform surgery and even h...","['they', 'assemble', 'cars', 'perform', 'surge...",1187
7,https://www.bbc.com/news/articles/c62jp09p0l4o,The fight against foreign developers buying Ca...,"On the small Caribbean island of Barbuda, the ...","['on', 'the', 'small', 'caribbean', 'island', ...",1346
8,https://www.bbc.com/future/article/20251218-ho...,"They hear, but do they care? What AI can teach...",AI chatbots don't interrupt and aren't judgeme...,"['ai', 'chatbots', 'don', 't', 'interrupt', 'a...",2335
9,https://www.bbc.com/news/articles/cvgzr935jvmo,University of Lincoln AI stand wins award at C...,An exhibition featuring a health scan for plan...,"['an', 'exhibition', 'featuring', 'a', 'health...",321

In [ ]:
# Checking datatype of token
print(type(df["tokens"].iloc[0]))
print(df["tokens"].iloc[0][:20])

<class 'str'>
['it', 'is', 'not',

In [ ]:
# ── SECTION 1.2: Convert token strings back to actual lists ──
# When pandas reads a CSV, everything comes in as a string
# ast.literal_eval() safely converts that string BACK into a real list.
import ast
df["tokens"] = df["tokens"].apply(ast.literal_eval)

# BM25 and text splitters work on strings
df["clean_text"] = [" ".join(x) for x in df["tokens"]] # Join the token list back into a single string sentence.
df

# Keep only the columns we'll actually use downstream
df = df[["url", "title", "clean_text"]]

In [ ]:
!pip install langchain-text-splitters

Requirement already satisfied: langchain-text-splitters in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in /usr/local/lib/python3.12/dist-packages (from langchain-text-splitters) (1.4.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.0.15)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.8.5)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (26.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.1.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.34.2)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.5.0)

In [ ]:
# ── SECTION 1.3: Split articles into smaller chunks ──────────
# Gemini has a context window limit — you can't dump 10 full articles.

from langchain_text_splitters import RecursiveCharacterTextSplitter as rts

# So we break each article into overlapping pieces of ~1000 characters.
# chunk_overlap=200 means consecutive chunks share 200 characters.
txt_spliter = rts(chunk_size= 1000, chunk_overlap=200)

all_chunks = []

for i in range(len(df)):
    text = df.loc[i, "clean_text"]
    title = df.loc[i, "title"]
    url = df.loc[i, "url"]

    pieces = txt_spliter.split_text(text) # split_text returns a list of string pieces

    # Store each chunk with metadata so we know which article it came from
    for j in range(len(pieces)):
        all_chunks.append({
            "article_id": i, # which article this chunk belongs to
            "chunk_id": j, # which piece within that article
            "title": title,
            "url": url,
            "text": pieces[j]
        })

print("Total chunks made:", len(all_chunks))
print(all_chunks[0])
print(all_chunks[1])

Total chunks made: 91
{'article_id': 0, 'chunk_id': 0, 'title': 'Why the AI industry is the real winner of the Musk-Altman trial', 'url': 'https://www.bbc.com/news/articles/crlp991nw41o', 'text': 'it is not only openai but the ai race itself that was vindicated in the california courtroom last night even though elon musk essentially lost on a technicality there s a clear signal from the verdict that making lots of money from ai and competing fiercely with rivals is simply business the industry sometimes tries to display a united front especially when it comes to safety research and inclusivity but this case served as a powerful reminder that none of the ai giants are charities and don t have to be even if they once said otherwise cracks in the façade of industry collaboration for the sake of humanity have been exposed before in february i was in india for a global ai summit where host prime minister narendra modi orchestrated the world s tech leaders to hold hands on stage sam altman and anthropic boss dario amodei once colleagues at openai and now bitter rivals found themselves side by side this time they pointedly clenched their fists into tight balls to avoid touching one'}
{'article_id': 0, 'chunk_id': 1, 'title': 'Why the AI industry is the real winner of the Musk-Altman trial', 'url': 'https://www.bbc.com/news/articles/crlp991nw41o', 'text': 'and anthropic boss dario amodei once colleagues at openai and now bitter rivals found themselves side by side this time they pointedly clenched their fists into tight balls to avoid touching one another similarly petty drama during the trial in oakland california these last weeks has helped lift the veil on the ai sector and the huge egos of the men at the heart of it jostling for money and power nobody came out of it looking particularly heroic amid a chorus of concern that ai firms have been overvalued and the sector could be a bubble about to burst the trial may have bought the industry more time some also speculated that openai could not afford to lose the company has burned through huge volumes of investor cash and recently hired a chief revenue officer denise dresser to help raise its own money i met dresser who joined openai from slack the us based team communication platform a few days ago she would not discuss the case but told me the chatgpt maker plans to raise 50 of its'}

In [ ]:
# New datafarame
df = pd.DataFrame(all_chunks)
df

,article_id,chunk_id,title,url,text
0,0,0,Why the AI industry is the real winner of the ...,https://www.bbc.com/news/articles/crlp991nw41o,it is not only openai but the ai race itself t...
1,0,1,Why the AI industry is the real winner of the ...,https://www.bbc.com/news/articles/crlp991nw41o,and anthropic boss dario amodei once colleague...
2,0,2,Why the AI industry is the real winner of the ...,https://www.bbc.com/news/articles/crlp991nw41o,its own money i met dresser who joined openai ...
3,0,3,Why the AI industry is the real winner of the ...,https://www.bbc.com/news/articles/crlp991nw41o,is not his first rodeo in courtroom dramas and...
4,0,4,Why the AI industry is the real winner of the ...,https://www.bbc.com/news/articles/crlp991nw41o,value in ai but it also exposed some of the im...
...,...,...,...,...,...
86,8,16,"They hear, but do they care? What AI can teach...",https://www.bbc.com/future/article/20251218-ho...,flying fears persist despite falling accident ...
87,8,17,"They hear, but do they care? What AI can teach...",https://www.bbc.com/future/article/20251218-ho...,at first overlooked whistler s 1871 painting o...
88,9,0,University of Lincoln AI stand wins award at C...,https://www.bbc.com/news/articles/cvgzr935jvmo,an exhibition featuring a health scan for plan...
89,9,1,University of Lincoln AI stand wins award at C...,https://www.bbc.com/news/articles/cvgzr935jvmo,said one of the most rewarding aspects we ve a...
90,9,2,University of Lincoln AI stand wins award at C...,https://www.bbc.com/news/articles/cvgzr935jvmo,flower also represents the very best of britis...

In [ ]:
# ── SECTION 1.4: Save chunks to CSV ─────────────────
df.to_csv("chunked_corpus.csv", index=False)
print("Saved chunked_corpus.csv")

Saved chunked_corpus.csv

## Hierarchical PageIndex

In [ ]:
!pip install fpdf

Requirement already satisfied: fpdf in /usr/local/lib/python3.12/dist-packages (1.7.2)

In [ ]:
# ── SECTION 2.1: Save chunks to PDF ─────────────────
# Why PDF? Because PageIndex accepts only PDFs as input.

import pandas as pd
from fpdf import FPDF

df = pd.read_csv("chunked_corpus.csv")

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15) # auto-adds new pages when full

for i in range(len(df)):
    title = str(df.loc[i, "title"])
    text = str(df.loc[i, "text"])
    url = str(df.loc[i, "url"])

    pdf.add_page()

    # Bold, larger font for the title
    pdf.set_font("Arial", "B", 14)
    pdf.multi_cell(0, 10, f"Title: {title}")

    # Smaller font for the URL
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 8, f"URL: {url}")

    pdf.ln(2)  # small vertical gap

    # Regular font for the chunk text
    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 8, text)

pdf.output("chunked_corpus.pdf")
print("PDF created: chunked_corpus.pdf")

PDF created: chunked_corpus.pdf

In [ ]:
# ── SECTION 2.2: Index the PDF with PageIndex ────────────────
from pageindex import PageIndexClient
pi_client = PageIndexClient(api_key=PAGEINDEX_API_KEY)

import pageindex.utils as utils

doc = pi_client.submit_document("chunked_corpus.pdf") # Submit the PDF to PageIndex for processing.
doc_id = doc["doc_id"]

while not pi_client.is_retrieval_ready(doc_id):
    print("Still indexing...")
    import time
    time.sleep(5)

tree = pi_client.get_tree(doc_id, node_summary=True)["result"] # Fetch the full document tree with node summaries

print("Document Tree:")
utils.print_tree(tree) # prints the hierarchy

Still indexing...
Still indexing...
Still indexing...
Document Tree:
[{'title': 'Title: Why the AI industry is the real w...',
  'node_id': '0000',
  'summary': 'The Musk-Altman trial verdict confirmed ...'},
 {'title': "Title: Google's AI is being manipulated....",
  'node_id': '0001',
  'prefix_summary': 'A BBC investigation reveals that AI chat...',
  'nodes': [{'title': 'The Vulnerability of AI to Online Manipu...',
             'node_id': '0002',
             'summary': 'A BBC investigation highlights how AI ch...'},
            {'title': 'The Ongoing Battle Against AI Search Man...',
             'node_id': '0003',
             'summary': 'The text explores the systemic manipulat...'},
            {'title': 'The Evolving AI Landscape and Global Tec...',
             'node_id': '0004',
             'summary': 'The text discusses the ongoing struggle ...'},
            {'title': 'Technological Innovations and Diverse Me...',
             'node_id': '0005',
             'summary': 'The text provides a broad collection of ...'}]},
 {'title': 'Title: Google to release first smart gla...',
  'node_id': '0006',
  'summary': 'Google is set to release new AI-powered ...'},
 {'title': 'Title: Standard Chartered to cut thousan...',
  'node_id': '0007',
  'summary': 'Standard Chartered is cutting over 7,800...'},
 {'title': 'Title: Samsung strike on hold as workers...',
  'node_id': '0008',
  'summary': "Samsung Electronics' largest union has s..."},
 {'title': "Title: 'Think outside the bots': How to ...",
  'node_id': '0009',
  'prefix_summary': 'The text explores growing scientific con...',
  'nodes': [{'title': 'The Cognitive Cost of AI: Balancing Outs...',
             'node_id': '0010',
             'summary': 'This text explores the potential cogniti...'},
            {'title': 'Preserving Cognitive Fitness in the Age ...',
             'node_id': '0011',
             'summary': 'The text explores the cognitive risks of...'},
            {'title': 'Preserving Human Cognition and Creativit...',
             'node_id': '0012',
             'summary': 'The text advocates for maintaining cogni...'},
            {'title': 'Technological Frontiers: From AI Innovat...',
             'node_id': '0013',
             'summary': 'This text provides a broad overview of c...'}]},
 {'title': 'Title: Robo-top: The machines that could...',
  'node_id': '0014',
  'prefix_summary': 'While most industries are highly automat...',
  'nodes': [{'title': 'The Future of Automated Apparel Manufact...',
             'node_id': '0015',
             'summary': 'While traditional garment manufacturing ...'},
            {'title': 'The Future of Automated Garment Manufact...',
             'node_id': '0016',
             'summary': 'The text explores the rise of sewing and...'},
            {'title': 'Textile Automation Challenges and Region...',
             'node_id': '0017',
             'summary': 'This text discusses the complexities and...'}]},
 {'title': 'Title: The fight against foreign develop...',
  'node_id': '0018',
  'prefix_summary': 'The text details the destruction of the ...',
  'nodes': [{'title': 'The Conflict Over Communal Land Rights a...',
             'node_id': '0019',
             'summary': 'This text details the struggle of Barbud...'},
            {'title': 'The Conflict Between Tourism Development...',
             'node_id': '0020',
             'summary': 'This text examines the conflict between ...'},
            {'title': 'The Socio-Economic and Environmental Imp...',
             'node_id': '0021',
             'summary': 'This text examines the conflict between ...'}]},
 {'title': 'Title: They hear, but do they care? What...',
  'node_id': '0022',
  'prefix_summary': 'The text explores how AI chatbots, by pr...',
  'nodes': [{'title': 'Learning the Art of Deep Listening from ...',
             'node_id': '0023',
             'summary': 'This text explores why people are increa...'},
            {'title': 'Lessons in Empathy: What AI Listening Ca...',
             'node_id': '0024',
             'summary': "This text explores how AI's listening be..."},
            {'title': 'Learning from Algorithms: The Potential ...',
             'node_id': '0025',
             'summary': 'This text explores how AI can serve as a...'},
            {'title': 'The Limits of AI Empathy and a Survey of...',
             'node_id': '0026',
             'summary': 'This text discusses the limitations and ...'},
            {'title': 'Technological Frontiers: From AI Innovat...',
             'node_id': '0027',
             'summary': 'This text provides a diverse overview of...'}]},
 {'title': 'Title: University of Lincoln AI stand wi...',
  'node_id': '0028',
  'summary': 'The University of Lincoln received a sil...'}]

## BM25 Retrieval — Implementation

In [ ]:
# ── SECTION 3.1: Flatten the tree into a list of nodes ───────
# BM25 needs a flat list of text chunks to score.
# So we walk the tree recursively and collect every node's summary text.

documents = [] # will hold one dict per tree node

""" Recursively walks through the PageIndex tree.

    Each node has:
    - node_id: unique ID
    - title: heading/label for this section
    - summary: a short auto-generated description of this section
    - nodes: list of child nodes (may be empty for leaf nodes)

    We prefer 'summary' over 'prefix_summary' because summary is
    usually more complete. prefix_summary is a fallback."""

def traverse_tree(node, parent_id=None, level=0):
    node_id = node.get("node_id", "")
    title = node.get("title", "")
    summary = node.get("summary", "")
    prefix_summary = node.get("prefix_summary", "")

    text = summary if summary else prefix_summary

    documents.append({
        "node_id": node_id,
        "parent_id": parent_id, # track the hierarchy
        "level": level, # depth in the tree — root=0, children=1, etc.
        "title": title,
        "text": text
    })

    # Recurse into children if any exist
    if "nodes" in node:
        for child in node["nodes"]:
            traverse_tree(child, parent_id=node_id, level=level + 1)

# Start traversal from every top-level node
for top_node in tree:
    traverse_tree(top_node)

In [ ]:
# ── SECTION 3.2: Build the BM25 Index ───────────────────────
from rank_bm25 import BM25Okapi

# convert each node text into tokens
tokenized_corpus = []

for doc in documents:
    tokens = doc["text"].split()
    tokenized_corpus.append(tokens)

# build BM25 index
bm25 = BM25Okapi(tokenized_corpus)

print("BM25 index built")
print("Number of documents in BM25:", len(tokenized_corpus))

BM25 index built
Number of documents in BM25: 29

In [ ]:
# ── SECTION 3.3: Test a raw BM25 query ──────────────────────
query = "AI manipulation of search results"
query_tokens = query.lower().split()

scores = bm25.get_scores(query_tokens)
print(scores)

# get indices of top 3 matching docs
top_n = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:3]

for i in top_n:
    print("Score:", scores[i])
    print("Title:", documents[i]["title"])
    print("Text:", documents[i]["text"])
    print("-" * 50)

[1.0364215  2.80594289 2.24713515 7.87352831 0.94544208 0.99734519
 0.         1.06041113 0.89498459 2.23908872 2.31543696 0.90614464
 0.95371416 1.11410441 0.79185511 0.64249707 1.16130991 0.65406281
 1.1203564  0.88409609 1.14906782 1.01593623 0.7332604  0.63133325
 0.         1.14604752 1.30461642 1.25129563 0.7002848 ]
Score: 7.873528306061369
Title: The Ongoing Battle Against AI Search Manipulation
Text: The text explores the systemic manipulation of AI search results and the potential dangers of biased or inaccurate information in critical areas like health and law. It details Google's efforts to combat this through updated spam policies and silent algorithmic adjustments, such as filtering out self-promotional content and adding transparency labels. Despite these interventions, experts remain skeptical, noting that manipulators continuously evolve their tactics—such as leveraging social media influencers—to circumvent new rules, leaving AI companies in a persistent, reactive struggle to maintain result integrity.
--------------------------------------------------
Score: 2.8059428868592873
Title: Title: Google's AI is being manipulated. The search giant is quietly fighting back
Text: A BBC investigation reveals that AI chatbots and search tools are being manipulated to spread misinformation, a vulnerability currently being exploited by companies. The author demonstrates the ease of this manipulation, prompting Google to update its policies in response to widespread criticism and research regarding the integrity of AI-generated content.
--------------------------------------------------
Score: 2.3154369612283405
Title: The Cognitive Cost of AI: Balancing Outsourcing and Mental Fitness
Text: This text explores the potential cognitive risks of over-relying on AI, drawing parallels to previous technological shifts like GPS and search engines. Experts warn that outsourcing mental labor to AI may lead to cognitive atrophy, as the 'struggle' of thinking is essential for brain health. While some research suggests technology can reduce cognitive impairment, current studies indicate that heavy AI use is linked to reduced critical thinking and a phenomenon called 'cognitive surrender.' Ultimately, the text suggests that the impact of AI depends on how it is used, emphasizing the need to balance tool usage with active mental engagement.
--------------------------------------------------

In [ ]:
# ── SECTION 3.4: Wrap BM25 as a LangChain Retriever ────────

from typing import List
from pydantic import Field
from langchain_core.documents import Document
from langchain_core.retrievers import BaseRetriever

# LangChain's retrieval chain expects a retriever object that follows its interface (a class with _get_relevant_documents method).
# We wrap our BM25 logic in that interface so it plugs in cleanly.
class BM25Retriever(BaseRetriever):
    bm25: object = Field()  # our BM25 index object
    docs: list   = Field()  # our flat list of node dicts
    k:    int    = 3        # how many top results to return

    def _get_relevant_documents(self, query: str) -> List[Document]:
        # convert query into tokens
        query_tokens = query.lower().split()

        # score all documents
        scores = self.bm25.get_scores(query_tokens)

        # get top k indices
        top_n = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:self.k]

        # convert results into LangChain Document objects
        results = []
        for i in top_n:
            results.append(
                Document(
                    page_content=self.docs[i]["text"],
                    metadata={
                        "node_id": self.docs[i]["node_id"],
                        "title": self.docs[i]["title"],
                        "score": float(scores[i])
                    }
                )
            )
        return results

In [ ]:
# create actual working retriever using our BM25 index
retriever = BM25Retriever(bm25=bm25, docs=documents, k=3)
print("Retriever ready")

Retriever ready

In [ ]:
# Quick test
results = retriever.invoke("AI manipulation of search results")

for doc in results:
    print(doc.metadata)
    print(doc.page_content)
    print("-" * 50)

{'node_id': '0003', 'title': 'The Ongoing Battle Against AI Search Manipulation', 'score': 7.873528306061369}
The text explores the systemic manipulation of AI search results and the potential dangers of biased or inaccurate information in critical areas like health and law. It details Google's efforts to combat this through updated spam policies and silent algorithmic adjustments, such as filtering out self-promotional content and adding transparency labels. Despite these interventions, experts remain skeptical, noting that manipulators continuously evolve their tactics—such as leveraging social media influencers—to circumvent new rules, leaving AI companies in a persistent, reactive struggle to maintain result integrity.
--------------------------------------------------
{'node_id': '0001', 'title': "Title: Google's AI is being manipulated. The search giant is quietly fighting back", 'score': 2.8059428868592873}
A BBC investigation reveals that AI chatbots and search tools are being manipulated to spread misinformation, a vulnerability currently being exploited by companies. The author demonstrates the ease of this manipulation, prompting Google to update its policies in response to widespread criticism and research regarding the integrity of AI-generated content.
--------------------------------------------------
{'node_id': '0010', 'title': 'The Cognitive Cost of AI: Balancing Outsourcing and Mental Fitness', 'score': 2.3154369612283405}
This text explores the potential cognitive risks of over-relying on AI, drawing parallels to previous technological shifts like GPS and search engines. Experts warn that outsourcing mental labor to AI may lead to cognitive atrophy, as the 'struggle' of thinking is essential for brain health. While some research suggests technology can reduce cognitive impairment, current studies indicate that heavy AI use is linked to reduced critical thinking and a phenomenon called 'cognitive surrender.' Ultimately, the text suggests that the impact of AI depends on how it is used, emphasizing the need to balance tool usage with active mental engagement.
--------------------------------------------------

## LangChain Integration

In [ ]:
!pip install -U langchain-classic

Requirement already satisfied: langchain-classic in /usr/local/lib/python3.12/dist-packages (1.0.7)
Requirement already satisfied: langchain-core<2.0.0,>=1.3.3 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (1.4.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (1.1.2)
Requirement already satisfied: langsmith<1.0.0,>=0.1.17 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (0.8.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.0.49)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.3->langchain-classic) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.3->langchain-classic) (0.0.15)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.3->langchain-classic) (26.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.3->langchain-classic) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.3->langchain-classic) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.3.3->langchain-classic) (0.16.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (2026.5.20)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-classic) (3.5.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.3.3->langchain-classic) (3.1.1)

In [51]:
# ── SECTION 4.1: Set up Gemini + Prompt ────────
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_classic.chains.retrieval import create_retrieval_chain

llm = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite") # We're using Gemini as the LLM here.

prompt = ChatPromptTemplate.from_template("""
Answer the question only using the context below.
If the answer is not present in the context, say: "Answer not found in the retrieved context."

Context: {context}

Question: {input}
""")

In [52]:
# ── SECTION 4.2: Run the RAG pipeline ──────────────────────

# takes retrieved docs and "stuffs" them all into the {context} slot of the prompt.
document_chain = create_stuff_documents_chain(llm, prompt)
# create_retrieval_chain: first runs the retriever, then passes the results to the document_chain.
retrieval_chain = create_retrieval_chain(retriever, document_chain)

response = retrieval_chain.invoke({
    "input": "How is AI being manipulated online?"
})

print(response["answer"])

AI is being manipulated by the use of simple, strategically published online content, which can force AI tools to generate biased or false information.

## Latency & Accuracy Comparison

In [57]:
# ── SECTION 5.1: Compare RAG vs Naive Full-Context ──────────
question = "How is AI being manipulated online?"

# naive: dump everything into the prompt
full_context    = " ".join(df["text"].astype(str).tolist())
formatted_prompt = prompt.format(context=full_context, input=question)

start       = time.perf_counter()
naive_answer = llm.invoke(formatted_prompt).content
naive_time  = time.perf_counter() - start

# rag: retriever picks top 3 chunks
start       = time.perf_counter()
rag_response = retrieval_chain.invoke({"input": question})
rag_time    = time.perf_counter() - start
rag_answer  = rag_response["answer"]
rag_chunks  = [doc.page_content for doc in rag_response["context"]]

In [58]:
!pip install deepeval

Requirement already satisfied: deepeval in /usr/local/lib/python3.12/dist-packages (4.0.5)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from deepeval) (3.13.5)
Requirement already satisfied: click<8.4.0,>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (8.3.3)
Requirement already satisfied: grpcio<2.0.0,>=1.67.1 in /usr/local/lib/python3.12/dist-packages (from deepeval) (1.80.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from deepeval) (3.1.6)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.12/dist-packages (from deepeval) (1.6.0)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (from deepeval) (2.37.0)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<2.0.0,>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (1.38.0)
Requirement already satisfied: portalocker in /usr/local/lib/python3.12/dist-packages (from deepeval) (3.2.0)
Requirement already satisfied: posthog<8.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (7.16.3)
Requirement already satisfied: pydantic<3.0.0,>=2.11.7 in /usr/local/lib/python3.12/dist-packages (from deepeval) (2.12.3)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from deepeval) (2.14.1)
Requirement already satisfied: pyfiglet in /usr/local/lib/python3.12/dist-packages (from deepeval) (1.0.4)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (from deepeval) (8.4.2)
Requirement already satisfied: pytest-asyncio in /usr/local/lib/python3.12/dist-packages (from deepeval) (1.4.0)
Requirement already satisfied: pytest-repeat in /usr/local/lib/python3.12/dist-packages (from deepeval) (0.9.4)
Requirement already satisfied: pytest-rerunfailures in /usr/local/lib/python3.12/dist-packages (from deepeval) (16.3)
Requirement already satisfied: pytest-xdist in /usr/local/lib/python3.12/dist-packages (from deepeval) (3.8.0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from deepeval) (1.2.2)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (2.34.2)
Requirement already satisfied: rich<15.0.0,>=13.6.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (13.9.4)
Requirement already satisfied: sentry-sdk in /usr/local/lib/python3.12/dist-packages (from deepeval) (2.60.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from deepeval) (75.2.0)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (0.9.0)
Requirement already satisfied: tenacity<=10.0.0,>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from deepeval) (9.1.4)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from deepeval) (4.67.3)
Requirement already satisfied: typer<1.0.0,>=0.9 in /usr/local/lib/python3.12/dist-packages (from deepeval) (0.25.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (from deepeval) (0.47.0)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.67.1->deepeval) (4.15.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api<2.0.0,>=1.24.0->deepeval) (8.7.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<2.0.0,>=1.24.0->deepeval) (0.59b0)
Requirement already satisfied: backoff>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from posthog<8.0.0,>=7.0.0->deepeval) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from posthog<8.0.0,>=7.0.0->deepeval) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->deepeval) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.31.0->deepeval) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=13.6.0->deepeval) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=13.6.0->deepeval) (2.20.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.9->deepeval) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.9->deepeval) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->deepeval) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->deepeval) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->deepeval) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->deepeval) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->deepeval) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->deepeval) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->deepeval) (1.24.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->deepeval) (3.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai->deepeval) (4.13.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai->deepeval) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai->deepeval) (0.15.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai->deepeval) (1.3.1)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest->deepeval) (2.3.0)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from pytest->deepeval) (26.2)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest->deepeval) (1.6.0)
Requirement already satisfied: execnet>=2.1 in /usr/local/lib/python3.12/dist-packages (from pytest-xdist->deepeval) (2.1.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai->deepeval) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->deepeval) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api<2.0.0,>=1.24.0->deepeval) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.6.0->deepeval) (0.1.2)

In [64]:
# ── SECTION 5.2: Accuracy comparison (DeepEval) ─────────────
from deepeval.test_case import LLMTestCase
from deepeval.metrics import ContextualRelevancyMetric, FaithfulnessMetric
from deepeval.models import GeminiModel

judge = GeminiModel(model="gemini-3.1-flash-lite")

# build one test case per method
naive_case = LLMTestCase(
    input=question,
    actual_output=naive_answer[0]["text"],
    retrieval_context=[full_context]  # one giant blob
)
rag_case = LLMTestCase(
    input=question,
    actual_output=rag_answer,
    retrieval_context=rag_chunks       # 3 targeted chunks
)

# run metrics on both
relevancy    = ContextualRelevancyMetric(threshold=0.7, model=judge)
faithfulness = FaithfulnessMetric(threshold=0.7, model=judge, include_reason=True)

relevancy.measure(naive_case)
naive_rel   = relevancy.score
faithfulness.measure(naive_case)
naive_faith = faithfulness.score

relevancy.measure(rag_case)
rag_rel     = relevancy.score
faithfulness.measure(rag_case)
rag_faith   = faithfulness.score

# final table
pd.DataFrame([
    {"method": "Naive full-context", "latency_sec": round(naive_time, 2), "relevancy": naive_rel,  "faithfulness": naive_faith},
    {"method": "BM25 RAG",           "latency_sec": round(rag_time, 2),   "relevancy": rag_rel,    "faithfulness": rag_faith}
])

Output()

Output()

Output()

Output()

               method  latency_sec  relevancy  faithfulness
0  Naive full-context         1.50   0.700000           1.0
1            BM25 RAG         0.57   0.666667           1.0